const BAFU_CONFIG = {
    chainId: 56,
    chainIdHex: '0x38',
    chainName: 'BNB Smart Chain',
    rpcUrl: 'https://bsc-dataseed.binance.org/',
    explorerUrl: 'https://bscscan.com',

    tokenContract: '0x0EA63C194D1Bd0887637C236069D44129442E0Ef',
    miningContract: '0x179E2BD8AcC6c4F4d1629b48AEA01601612Ce031',
    dynamicContract: '0xD7f20901E2623E711B8B1eBC73A70Ed041A6037A',
    nodeContract: '0x5D3fB89AE094BdfcB5df2b67BdE49264c29f490b',
    tradeContract: '0x3f7b92cd9340D37cC891D0352Ff1196168f4DBcb',

    bscUSDT: '0x55d398326f99059fF775485246999027B3197955',
    pancakeRouter: '0x10ED43C718714eb63d5aA57B78B54704E256024E',

    tokenName: '牛牛币',
    tokenSymbol: 'NNB',
    totalSupply: 21000000,
    initialPrice: 0.017,
};

const BAFU_ABI = {
    token: [
        'function name() view returns (string)',
        'function symbol() view returns (string)',
        'function decimals() view returns (uint8)',
        'function totalSupply() view returns (uint256)',
        'function balanceOf(address) view returns (uint256)',
        'function allowance(address,address) view returns (uint256)',
        'function approve(address,uint256) returns (bool)',
        'function transfer(address,uint256) returns (bool)',
    ],
    mining: [
        'function buyMiner(uint256 usdtAmount)',
        'function reinvest(uint256 nnbAmount)',
        'function claim()',
        'function settleRelease(address)',
        'function getMinerInfo(address) view returns (uint256,uint256,uint256,uint256,uint256,bool,uint256)',
        'function getDailyRelease(address) view returns (uint256)',
        'function nnbPrice() view returns (uint256)',
        'function totalSold() view returns (uint256)',
        'function maxSupply() view returns (uint256)',
        'function getRemainingSupply() view returns (uint256)',
        'function isPresaleActive() view returns (bool)',
        'function getUserId(address) view returns (uint256)',
        'function getAddressById(uint256) view returns (address)',
    ],
    dynamic: [
        'function registerReferral(address,address)',
        'function referrer(address) view returns (address)',
        'function getDirectReferrals(address) view returns (address[])',
        'function getDirectCount(address) view returns (uint256)',
        'function teamTotalUSD(address) view returns (uint256)',
        'function userMinerUSD(address) view returns (uint256)',
        'function getMaxGenerations(address) view returns (uint256)',
    ],
    node: [
        'function buyNormalNode()',
        'function buySuperNode()',
        'function claimDividend()',
        'function getNodeInfo(address) view returns (uint8,uint256,bool,uint256)',
        'function getNormalNodeCount() view returns (uint256)',
        'function getSuperNodeCount() view returns (uint256)',
        'function getAvailableDividend(address) view returns (uint256)',
    ],
    trade: [
        'function createSellOrder(uint256)',
        'function buyNNB(uint256)',
        'function cancelSellOrder(uint256)',
        'function subscribe(uint256)',
        'function cancelQueueOrder(uint256)',
        'function getSellOrderInfo(uint256) view returns (address,uint256,uint256,uint256,bool)',
        'function getActiveSellCount() view returns (uint256)',
        'function getQueueLength() view returns (uint256)',
        'function transferNNB(address,uint256)',
        'function transferNNBById(uint256,uint256)',
    ],
    usdt: [
        'function balanceOf(address) view returns (uint256)',
        'function approve(address,uint256) returns (bool)',
        'function allowance(address,address) view returns (uint256)',
    ],
};
